trigger:
  batch: false
  branches:
    include:
    - master
    - feature/*
    - release/*
    - dev/*
  paths:
    exclude:
    - docs
pr:
  - master
  - feature/*
  - release/*

variables:
- group: Sleet
- name: Configuration
  value: Release
- name: DotNetVersion
  value: 3.1.x

stages:

- stage: Build
  jobs:
  - job: Build
    pool:
      vmImage: 'windows-2019'
    steps:
    - checkout: self
      clean: true

    - task: UseDotNet@2
      inputs:
          version: $(DotNetVersion)
          performMultiLevelLookup: true

    - script: dotnet tool update -g dotnet-format
      displayName: Install dotnet-format

    - script: dotnet format --dry-run --check -v:diag
      displayName: Run dotnet-format to ensure compliance

    - task: MSBuild@1
      displayName: Restore
      inputs:
        solution: RxFree.sln
        configuration: $(Configuration)
        msbuildArguments: -t:restore

    - task: MSBuild@1
      displayName: Set Version
      inputs:
        solution: RxFree/RxFree.csproj
        msbuildArguments: -t:version

    - task: MSBuild@1
      displayName: Build
      inputs:
        solution: RxFree.sln
        configuration: $(Configuration)
        msbuildArguments: -p:GeneratePackageOnBuild=true -p:PackageOutputPath=$(Build.ArtifactStagingDirectory)

    - task: VSTest@2
      displayName: Test
      inputs:
        testAssemblyVer2: RxFree.Tests/bin/*/*.Tests.dll
        runInParallel: true
        codeCoverageEnabled: true
        publishRunAttachments: true
        diagnosticsEnabled: false
        rerunFailedTests: true

    - task: PublishBuildArtifacts@1
      displayName: Upload
      condition: succeeded()
      inputs:
        PathtoPublish: $(Build.ArtifactStagingDirectory)
        ArtifactName: package
        ArtifactType: Container

- stage: Deploy
  variables:
  - name: SleetVersion
    value: 2.3.33
  jobs:
  - deployment: Deploy
    pool:
      vmImage: 'windows-2019'
    environment: sleet
    strategy:
      runOnce:
        deploy:
          steps:
          - pwsh: |
             $anyinstalled = (dotnet tool list -g | select-string sleet) -ne $null
             Write-Host "##vso[task.setvariable variable=Sleet.AnyInstalled;]$anyinstalled"
   
             $sameinstalled = (dotnet tool list -g | select-string sleet | select-string $(SleetVersion)) -ne $null
             Write-Host "##vso[task.setvariable variable=Sleet.SameInstalled;]$sameinstalled"
            displayName: 'Check Sleet installed version'

          - task: DotNetCoreCLI@2
            displayName: 'Uninstall Sleet if necessary'
            continueOnError: true
            condition: and(eq(variables['Sleet.AnyInstalled'], 'True'), eq(variables['Sleet.SameInstalled'], 'False'))
            inputs:
              command: custom
              custom: tool
              arguments: 'uninstall -g Sleet'

          - task: DotNetCoreCLI@2
            displayName: 'Install Sleet if necessary'
            condition: eq(variables['Sleet.SameInstalled'], 'False')
            inputs:
              command: custom
              custom: tool
              arguments: 'install --global Sleet --version $(SleetVersion)'

          - task: DownloadPipelineArtifact@2
            inputs:
              artifactName: package

          - script: 'sleet push --config none $(Pipeline.Workspace)/package -f --verbose -p "SLEET_FEED_CONNECTIONSTRING=$(SLEET_FEED_CONNECTIONSTRING)"'
            displayName: 'Push package via Sleet'
